<?php
/**
 * @file
 * Code for the News feature.
 */

include_once('campuscms_feature_news.features.inc');

/**
 * Implements hook_form_alter().
 */
function campuscms_feature_news_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'news_node_form') {
    $form['#attached']['css'] = array(
      drupal_get_path('module', 'campuscms_feature_news') . '/campuscms-feature-news.css',
    );
  }
}
